#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# Zero-Cost Email Automation System — Interactive Setup Script
# Tested on: macOS 13+, Ubuntu 22.04, Windows 11 (WSL2)
# Run: chmod +x scripts/setup.sh && ./scripts/setup.sh
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()    { echo -e "${GREEN}✓${NC} $1"; }
warn()   { echo -e "${YELLOW}⚠${NC}  $1"; }
error()  { echo -e "${RED}✗${NC} $1"; exit 1; }
info()   { echo -e "${CYAN}ℹ${NC}  $1"; }
header() { echo -e "\n${BOLD}${BLUE}═══ $1 ═══${NC}\n"; }

# ── Detect OS ────────────────────────────────────────────────────────────────
OS="unknown"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then OS="linux"
elif [[ "$OSTYPE" == "darwin"* ]];  then OS="macos"
elif [[ "$OSTYPE" == "msys"* ]] || [[ "$OSTYPE" == "cygwin"* ]]; then OS="windows"
fi

header "Zero-Cost Email Automation — Setup Wizard"
echo "Platform: $OS | RAM: 8 GB optimized | Date: $(date '+%Y-%m-%d')"
echo ""
info "This script will guide you through setting up all components."
info "You will need: Gmail, Groq account, Google Cloud account."
echo ""

# ── Step 0: Check prerequisites ──────────────────────────────────────────────
header "Step 0: Checking Prerequisites"

check_cmd() {
  if command -v "$1" &>/dev/null; then
    log "$1 is installed ($(command -v $1))"
  else
    warn "$1 is NOT installed"
    echo "    Install from: $2"
    if [[ "$3" == "required" ]]; then
      error "Cannot continue without $1. Please install it and re-run."
    fi
  fi
}

check_cmd "docker"  "https://www.docker.com/products/docker-desktop/" "required"
check_cmd "git"     "https://git-scm.com/downloads" "optional"
check_cmd "curl"    "pre-installed on most systems" "optional"
check_cmd "python3" "https://python.org" "optional"

# Check Docker is running
if ! docker info &>/dev/null 2>&1; then
  error "Docker is installed but not running. Please start Docker Desktop and re-run."
fi
log "Docker is running"

# Check available RAM (Linux/macOS)
if [[ "$OS" == "linux" ]]; then
  AVAIL_MEM=$(free -m | awk '/^Mem:/{print $2}')
  if [[ $AVAIL_MEM -lt 4096 ]]; then
    warn "Low RAM detected: ${AVAIL_MEM}MB. Minimum recommended: 4096MB."
  else
    log "RAM check passed: ${AVAIL_MEM}MB available"
  fi
fi

# ── Step 1: Create .env file ─────────────────────────────────────────────────
header "Step 1: Configure Environment Variables"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  warn ".env file already exists. Skipping (delete it to reconfigure)."
else
  echo "I'll now collect your credentials. They stay LOCAL — never sent anywhere."
  echo ""

  # PostgreSQL password
  while true; do
    read -s -p "Enter a PostgreSQL password (min 12 chars): " PG_PASS
    echo ""
    if [[ ${#PG_PASS} -ge 12 ]]; then break
    else warn "Password too short. Try again."; fi
  done

  # n8n dashboard password
  while true; do
    read -s -p "Enter n8n dashboard password (min 12 chars): " N8N_PASS
    echo ""
    if [[ ${#N8N_PASS} -ge 12 ]]; then break
    else warn "Password too short. Try again."; fi
  done

  # Groq API key
  echo ""
  info "Get your FREE Groq API key at: https://console.groq.com"
  info "Sign up → API Keys → Create New Key (starts with gsk_)"
  read -p "Paste your Groq API key: " GROQ_KEY
  if [[ ! "$GROQ_KEY" =~ ^gsk_ ]]; then
    warn "Key doesn't start with gsk_ — double-check you copied it correctly."
  fi

  # Gmail
  echo ""
  info "Gmail setup: myaccount.google.com → Security → 2FA → App Passwords"
  info "Create an App Password named 'n8n Bot' and paste the 16-char password below."
  read -p "Your Gmail address: " GMAIL_ADDR
  read -s -p "Gmail App Password (16 chars, no spaces): " GMAIL_PASS
  echo ""

  # Google Sheets
  echo ""
  info "Google Sheets Spreadsheet ID:"
  info "Open your sheet → URL looks like: docs.google.com/spreadsheets/d/THIS_PART/edit"
  read -p "Paste your Spreadsheet ID: " SHEETS_ID

  # Personal details
  echo ""
  read -p "Your name (for email sign-off): " YOUR_NAME
  read -p "Your company name: " YOUR_COMPANY

  # Write .env
  cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by setup.sh — $(date)
POSTGRES_PASSWORD=${PG_PASS}
N8N_PASSWORD=${N8N_PASS}
GROQ_API_KEY=${GROQ_KEY}
GMAIL_ADDRESS=${GMAIL_ADDR}
GMAIL_APP_PASSWORD=${GMAIL_PASS}
GOOGLE_SHEETS_SPREADSHEET_ID=${SHEETS_ID}
YOUR_NAME=${YOUR_NAME}
YOUR_COMPANY=${YOUR_COMPANY}
ENVEOF

  chmod 600 "$ENV_FILE"
  log ".env created with permissions 600 (owner-only read)"
fi

# ── Step 2: Update business_context.json ─────────────────────────────────────
header "Step 2: Personalizing Business Context"

# Load env vars
set -a; source "$ENV_FILE"; set +a

BIZ_FILE="$PROJECT_DIR/business_context.json"
if [[ -f "$BIZ_FILE" ]]; then
  # Replace placeholder values
  sed -i.bak \
    -e "s/YOUR COMPANY NAME/${YOUR_COMPANY:-Your Company}/g" \
    -e "s/reddykrishnakrishna548@gmail.com/${GMAIL_ADDRESS:-reddykrishnakrishna548@gmail.com}/g" \
    -e "s/Krishna/${YOUR_NAME:-Krishna}/g" \
    -e "s/yourwebsite.com/yourwebsite.com/g" \
    "$BIZ_FILE"
  rm -f "${BIZ_FILE}.bak"
  log "business_context.json personalized"
fi

# ── Step 3: Update n8n workflow JSONs with real values ───────────────────────
header "Step 3: Patching n8n Workflow Files"

WORKFLOWS_DIR="$PROJECT_DIR/n8n-workflows"
for f in "$WORKFLOWS_DIR"/*.json; do
  sed -i.bak \
    -e "s/YOUR_SPREADSHEET_ID/${GOOGLE_SHEETS_SPREADSHEET_ID:-YOUR_SPREADSHEET_ID}/g" \
    -e "s/reddykrishnakrishna548@gmail.com/${GMAIL_ADDRESS:-reddykrishnakrishna548@gmail.com}/g" \
    -e "s/YOUR COMPANY/${YOUR_COMPANY:-Your Company}/g" \
    -e "s/Krishna/${YOUR_NAME:-Krishna}/g" \
    "$f"
  rm -f "${f}.bak"
done
log "Workflow JSONs patched with your details"

# ── Step 4: Update SQL seed data ──────────────────────────────────────────────
header "Step 4: Patching Database Seed Data"

SQL_FILE="$PROJECT_DIR/sql/init.sql"
sed -i.bak \
  -e "s/reddykrishnakrishna548@gmail.com/${GMAIL_ADDRESS:-reddykrishnakrishna548@gmail.com}/g" \
  "$SQL_FILE"
rm -f "${SQL_FILE}.bak"
log "init.sql patched"

# ── Step 5: Docker Compose ───────────────────────────────────────────────────
header "Step 5: Starting Docker Containers"

cd "$PROJECT_DIR"

info "Pulling Docker images (first run ~500MB download, ~2 min)..."
docker compose pull --quiet

info "Starting PostgreSQL and n8n..."
docker compose up -d

# Wait for health checks
info "Waiting for services to become healthy..."
for i in {1..30}; do
  PG_STATUS=$(docker inspect --format='{{.State.Health.Status}}' email_pg 2>/dev/null || echo "starting")
  N8N_STATUS=$(docker inspect --format='{{.State.Health.Status}}' n8n 2>/dev/null || echo "starting")

  if [[ "$PG_STATUS" == "healthy" ]] && [[ "$N8N_STATUS" == "healthy" ]]; then
    log "All services are healthy!"
    break
  fi

  if [[ $i -eq 30 ]]; then
    warn "Services taking longer than expected. Check: docker compose logs"
    break
  fi

  printf "."
  sleep 5
done
echo ""

# ── Step 6: Verify n8n is accessible ─────────────────────────────────────────
header "Step 6: Verifying Setup"

if curl -s -o /dev/null -w "%{http_code}" "http://localhost:5678/healthz" | grep -q "200"; then
  log "n8n dashboard is running at http://localhost:5678"
else
  warn "n8n not responding yet. Try: docker compose logs n8n"
fi

# Check postgres
if docker exec email_pg pg_isready -U n8n_user -d email_automation &>/dev/null; then
  log "PostgreSQL is accepting connections"
  # Verify tables
  TABLE_COUNT=$(docker exec email_pg psql -U n8n_user -d email_automation -t -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public';" 2>/dev/null | tr -d ' ')
  log "Database has ${TABLE_COUNT} tables created"
else
  warn "PostgreSQL health check failed. Check: docker compose logs postgres"
fi

# ── Step 7: Print next steps ─────────────────────────────────────────────────
header "🎉 Setup Complete! Next Steps"

echo -e "${BOLD}Your system is running. Here's what to do next:${NC}"
echo ""
echo -e "  ${GREEN}1.${NC} Open n8n:    ${CYAN}http://localhost:5678${NC}"
echo -e "     Login:     admin / [your N8N_PASSWORD]"
echo ""
echo -e "  ${GREEN}2.${NC} Import workflows (in n8n UI):"
echo -e "     Settings → Import Workflow"
echo -e "     Import these 3 files from:  n8n-workflows/"
echo -e "     ${CYAN}workflow_A_ingest_classify_draft.json${NC}"
echo -e "     ${CYAN}workflow_B_approval_send.json${NC}"
echo -e "     ${CYAN}workflow_C_watchdog.json${NC}"
echo ""
echo -e "  ${GREEN}3.${NC} Add credentials in n8n (Credentials → New):"
echo -e "     ${YELLOW}Gmail IMAP${NC}         → Email (IMAP) → imap.gmail.com:993"
echo -e "     ${YELLOW}Gmail SMTP${NC}         → SMTP → smtp.gmail.com:587"
echo -e "     ${YELLOW}Groq API Key${NC}       → HTTP Header Auth → Authorization: Bearer YOUR_KEY"
echo -e "     ${YELLOW}PostgreSQL Local${NC}   → PostgreSQL → localhost:5432"
echo -e "     ${YELLOW}Google Sheets${NC}      → Google Sheets OAuth2 (upload service account JSON)"
echo ""
echo -e "  ${GREEN}4.${NC} Create Google Sheet with these tabs:"
echo -e "     ${CYAN}EmailApprovals${NC} | ${CYAN}Analytics${NC} | ${CYAN}SentLog${NC} | ${CYAN}Blocklist${NC}"
echo ""
echo -e "  ${GREEN}5.${NC} Edit business_context.json with your real company info"
echo ""
echo -e "  ${GREEN}6.${NC} Activate all 3 workflows in n8n (toggle ON)"
echo ""
echo -e "  ${GREEN}7.${NC} Send yourself a test email and watch it appear in:"
echo -e "     n8n executions → Google Sheets EmailApprovals tab"
echo ""
echo -e "${BOLD}Optional — Remote access via Cloudflare:${NC}"
echo -e "  brew install cloudflare/cloudflare/cloudflared"
echo -e "  cloudflared tunnel --url http://localhost:5678"
echo ""
echo -e "${BOLD}Optional — Offline LLM fallback (Ollama):${NC}"
echo -e "  docker compose --profile offline up -d"
echo -e "  docker exec ollama ollama pull llama3:8b"
echo ""
log "All implementation files are in: $PROJECT_DIR"
echo ""
